### ISSUE TITLE
Buggy SetURL in UIA_Browser

### ISSUE THREAD

**Issue by enaaab460** [Descolada/UIA-v2#43]
After V1, Seturl method adds a space and l (as in " l") at the end of the url using Chrome.

To fix it on my end, I reverted it to the past behavior , which is focus url edit box and send enter

Lines 798-799

**Comment by Descolada** [comment]
The spacebar has always been added to prevent an accidental auto-complete with some other URL that was autosuggested. Why the "l" is added I'm not too sure. Can you try whether replacing line 799 with `ControlSend "{LCtrl up}{LAlt up}{LShift up}{RCtrl up}{RAlt up}{RShift up}{Ctrl down}{Ctrl down}l{Ctrl up}{Enter}", , "ahk_id" this.BrowserId` changes anything?

Otherwise, have you changed your default `SetKeyDelay` values?

**Comment by enaaab460** [comment]
> Otherwise, have you changed your default `SetKeyDelay` values?

Yes
I have SetKeyDelay(-1, -1)
When I commented it out, it worked
That said, 
```
this.URLEditElement.SetFocus()
ControlSend "{Enter}", , this.BrowserId
```
in Lines 798-799 works without having to comment out setkeydelay


>ControlSend "{LCtrl up}{LAlt up}{LShift up}{RCtrl up}{RAlt up}{RShift up}{Ctrl down}{Ctrl down}l{Ctrl up}{Enter}", , "ahk_id" this.BrowserId

Still doesn't work
![image](https://github.com/user-attachments/assets/e0972282-6345-4ecd-a26b-55c7ef9a471e)

**Comment by Descolada** [comment]
I've pushed an update to try and fix this issue. Please see if the latest UIA_Browser works for you.

**Comment by enaaab460** [comment]
> I've pushed an update to try and fix this issue. Please see if the latest UIA_Browser works for you.

It works now
Thanks!

**Comment by aaronm32** [comment]
I am still having this issue in the latest version v2-1.0.2.  SetKeyDelay is the default (unchanged).  When using chrome and running seturl("https://www.hulu.com/watch/bf5b0d1a-b99b-492b-9748-86ff5a0669dc") it adds an extra " l" at the end of the url.  It doesn't happen with every url, just certain values occasionally.

**Comment by Descolada** [comment]
UIA_Browser.SetUrl uses UIA_Browser.ControlSend to send the keystrokes, and SetKeyDelay doesn't affect it. Try manually changing the values of `SetKeyDelay -1, 1` line in that method, for example `SetKeyDelay 0,1` or `SetKeyDelay 1,1`. I tried to find a compromise between speed and reliability but obviously I failed :)

**Comment by aaronm32** [comment]
It's something strange with UIA_Browser.SetUrl using `this.URLEditElement.ValuePattern.SetValue(newUrl " ")` causing the extra 'l' in the value.  If I comment that line out, it then runs `this.URLEditElement.LegacyIAccessiblePattern` and that one works.

**Comment by aaronm32** [comment]
Ah, I see.  I cleared my browser history and it works with that url.  If the purpose of ctrl+l is to highlight the address bar text then another option might be to use all modifiers so it won't accidentally get added to the url.  Something like send `{home}{shift  down}{end}{shift up}`

**Comment by aaronm32** [comment]
Yes, clearing the browser history fixed it.  I played around to see if there is a universal special char that will go to the address bar and it's F6.  In Chrome and Firefox a single F6 works and in MS Edge it takes F6+F6.  So what seems to work universally is send `{F6}{Enter}{F6}{Enter}` and that way no characters will inadvertently get added to the url.
